[ACCOUNT]
  atxi = false
  "atxi.autobuild" = false
  index-accounts = false
  keystore = ""
  password = ""
  unlock = ""

["API AND CONSOLE"]
  exec = ""
  ipc-api = ["admin", "debug", "eth", "miner", "net", "personal", "shh", "txpool", "web3", "geth"]
  ipc-disable = false
  ipc-path = "geth.ipc"
  js-path = "."
  preload = ""
  rpc = false
  rpc-addr = "localhost"
  rpc-api = ["eth", "net", "web3"]
  rpc-cors-domain = ""
  rpc-port = 8545
  ws = false
  ws-addr = "localhost"
  ws-api = ["eth", "net", "web3"]
  ws-origins = ""
  ws-port = 8546

[ETHEREUM]
  blockchain-version = 3
  cache = 1024
  chain = "mainnet"
  data-dir = "/Users/ia/Library/EthereumClassic"
  dev = false
  fast = false
  identity = ""
  light-kdf = false
  network-id = 1
  sputnikvm = false

[EXPERIMENTAL]
  natspec = false
  shh = false

["GAS PRICE ORACLE"]
  gpo-base-cf = 110
  gpo-base-down = 10
  gpo-base-up = 100
  gpo-full = 80
  gpo-max = "500000000000"
  gpo-min = "20000000000"

[LEGACY]
  oppose-dao-fork = false
  testnet = false

["LOGGING AND DEBUGGING"]
  display = 3
  display-fmt = "basic"
  fake-pow = false
  log-compress = true
  log-dir = "/Users/ia/Library/EthereumClassic/<chain>/log"
  log-max-age = "0"
  log-max-size = "30M"
  log-min-size = "0"
  log-rotation-interval = "hourly"
  log-status = "sync=60s"
  log-total-max-size = "0"
  metrics = ""
  mlog = "off"
  mlog-components = ["state", "headerchain", "txpool", "downloader", "fetcher", "miner", "discover", "blockchain", "wire", "server"]
  mlog-dir = "/Users/ia/Library/EthereumClassic/mainnet/mlogs"
  neckbeard = false
  pprof = 0
  pprof-interval = 5
  verbosity = 5
  vmodule = ""
  ["LOGGING AND DEBUGGING".backtrace]

[MINER]
  auto-dag = false
  etherbase = "0"
  extra-data = ""
  gas-price = "20000000000"
  mine = false
  miner-gpus = ""
  miner-threads = 2
  target-gas-limit = "4712388"

[MISCELLANEOUS]
  solc = "solc"

[NETWORKING]
  bootnodes = ""
  doc-root = "/Users/ia"
  max-peers = 25
  max-pend-peers = 0
  nat = "any"
  no-discover = false
  nodekey = ""
  nodekey-hex = ""
  port = 30303
